env:
  commonjs: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules: {}
globals:
  Buffer: true
  setTimeout: true
  module: true
  require: true
  process: true
  console: true
